[
  {
    email: "alice@example.com",
    password: "password@123",
    fName: "Alice",
    lName: "Smith",
    bio: "Lover of books and coffee.",
    profile: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    email: "bob@example.com",
    password: "password@123",
    fName: "Bob",
    lName: "Johnson",
    bio: "Tech enthusiast and gamer.",
    profile: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    email: "carol@example.com",
    password: "password@123",
    fName: "Carol",
    lName: "Williams",
    bio: "Traveler and food lover.",
    profile: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    email: "dave@example.com",
    password: "password@123",
    fName: "Dave",
    lName: "Brown",
    bio: "Fitness enthusiast and photographer.",
    profile: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    email: "eve@example.com",
    password: "password@123",
    fName: "Eve",
    lName: "Davis",
    bio: "Music lover and artist.",
    profile: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    email: "frank@example.com",
    password: "password@123",
    fName: "Frank",
    lName: "Miller",
    bio: "Gamer and movie buff.",
    profile: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    email: "grace@example.com",
    password: "password@123",
    fName: "Grace",
    lName: "Wilson",
    bio: "Nature lover and writer.",
    profile: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    email: "henry@example.com",
    password: "password@123",
    fName: "Henry",
    lName: "Moore",
    bio: "History buff and chef.",
    profile: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    email: "isla@example.com",
    password: "password@123",
    fName: "Isla",
    lName: "Taylor",
    bio: "Fashionista and traveler.",
    profile: "https://randomuser.me/api/portraits/women/5.jpg",
  },
];
